#!/usr/bin/env bash
# Pure-Zeus install setup for sglang.
#
# Builds a generated editable-install project under `python/.zeus_editable`
# so pip resolves the `[srt_zeus]` extra against the multi-backend
# `pyproject_other.toml` without pulling CUDA build dependencies and without
# mutating tracked pyproject files.
#
# After this script:
#   - python/pyproject.toml and python/pyproject_other.toml remain untouched
#   - python/.zeus_editable/ contains generated symlinks + pyproject.toml
#   - sglang installed editable with [srt_zeus] extra
#
# Prerequisites:
#   - python>=3.13 venv active (see zeus_dev/zeus_install.md §0 for box layout)
#   - torch_zeus + sgl_kernel_zeus already installed from their source trees
#     (see zeus_dev/zeus_install.md §1)
#   - rust toolchain (only required if outlines_core==0.1.26 wheel is missing
#     for your interpreter)

set -euo pipefail

REPO_ROOT="$(git rev-parse --show-toplevel)"
cd "$REPO_ROOT"

if [[ ! -f python/pyproject_other.toml ]]; then
  echo "error: python/pyproject_other.toml not found." >&2
  echo "  Restore it from git or run this from the sglang repo." >&2
  exit 1
fi

ZEUS_PROJECT_DIR="$REPO_ROOT/python/.zeus_editable"

echo "[zeus-setup] generating editable project at python/.zeus_editable"
rm -rf "$ZEUS_PROJECT_DIR"
mkdir -p "$ZEUS_PROJECT_DIR"

cp python/pyproject_other.toml "$ZEUS_PROJECT_DIR/pyproject.toml"
ln -s "$REPO_ROOT/python/sglang" "$ZEUS_PROJECT_DIR/sglang"
ln -s "$REPO_ROOT/LICENSE" "$ZEUS_PROJECT_DIR/LICENSE"

# pyproject_other.toml declares readme = "README.md". The upstream python/
# package tree does not carry one, so provide a tiny generated readme to keep
# modern build frontends from failing metadata validation.
cat > "$ZEUS_PROJECT_DIR/README.md" <<'EOF'
SGLang Zeus editable install project generated by zeus_dev/setup_zeus_dev.sh.
EOF

echo "[zeus-setup] pip install -e \"python/.zeus_editable[srt_zeus]\" --no-build-isolation"
pip install -e "python/.zeus_editable[srt_zeus]" --no-build-isolation

echo
echo "[zeus-setup] done. Tracked pyproject files were not modified."
